// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZ-nsllCQPgPOU6aYpELdqkUwFbe-EZw',
    appId: '1:1021080087660:web:e6da93a468cc463a0efc49',
    messagingSenderId: '1021080087660',
    projectId: 'whatsapp-backend-2abf9',
    authDomain: 'whatsapp-backend-2abf9.firebaseapp.com',
    storageBucket: 'whatsapp-backend-2abf9.appspot.com',
    measurementId: 'G-7P0RCC8BQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0NBt0Ny4HyZsmJclBaQJk9d0lM0uNPU',
    appId: '1:1021080087660:android:009ed48cb51c9eab0efc49',
    messagingSenderId: '1021080087660',
    projectId: 'whatsapp-backend-2abf9',
    storageBucket: 'whatsapp-backend-2abf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDykowCIJKJQAShNw-kwmjfMNSXkH0Flyk',
    appId: '1:1021080087660:ios:e5459d99c35116700efc49',
    messagingSenderId: '1021080087660',
    projectId: 'whatsapp-backend-2abf9',
    storageBucket: 'whatsapp-backend-2abf9.appspot.com',
    iosClientId: '1021080087660-c4jm69fbbmv997fc11ghbg0fbu247pfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDykowCIJKJQAShNw-kwmjfMNSXkH0Flyk',
    appId: '1:1021080087660:ios:e5459d99c35116700efc49',
    messagingSenderId: '1021080087660',
    projectId: 'whatsapp-backend-2abf9',
    storageBucket: 'whatsapp-backend-2abf9.appspot.com',
    iosClientId: '1021080087660-c4jm69fbbmv997fc11ghbg0fbu247pfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
